docker:
    path: .
id: 07496a77-7374-4d46-8833-f17017179d13
name: niels-capstone-3
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: pyspark
version: "0.3"
workflows:
    path: dags
    version: "2"
