docker:
    path: .
id: 18a454f0-fe00-4eb3-9a7d-7c657756e461
name: niels-capstone-2
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: pyspark
version: "0.3"
workflows:
    path: dags
    version: "2"
